// Write a JavaScript program to create an object with keys generated by running the provided function
// for each key and the same values as the provided object.

let key_generated = (obj, fn) => 
    Object.keys(obj).reduce((ac, av) => 
        (ac[fn(obj[av], av)] = obj[av],ac), {})

console.log(key_generated({A: 1, B: 2}, (val, acc) => acc + val))